feat: sticker create #21
Pic-me-Pic-me/Pic.me-server pull request #22
Opened 2023-01-05 19:44 UTC by dragontaek-lee

## 🖼️ 작업한 내용
- `스티커 찹`을 구현하였습니다

## 📸 PR Point

- `transaction`을 사용합니다 
- 해당 API는 `동시성 제어`가 필수입니다
- `count` 가 동시에 증가되면 안되고, 특히 배열 부분이 동시에 섞이면 안됩니다

## ✍️ 관련 이슈
- Resolved: #21

2023-01-05 22:04 UTC, wlwpfh submitted a review, later dismissed
트랜잭션까지 신경쓰고 넘 수고 많았습니다 👍👍👍👍 배워가요 ~ ~

2023-01-05 22:04 UTC, wlwpfh commented on src/service/stickerService.ts
> +                });
👍👍👍 뒤에 붙일 때 push로만 하면 되는군요! 알아갑니다~

2023-01-05 22:04 UTC, wlwpfh commented on src/service/stickerService.ts
> +            );
트랜잭션 안에서 findSticker함수를 불러오는 것이어서 인자로 tx를 넘겨주는 건가요?!!

2023-01-06 04:34 UTC, dragontaek-lee commented on src/service/stickerService.ts
> +            );
넵!! 코드가 너무 더러워서 그렇게 해놨어요.>!>!>!>!

2023-01-06 05:24 UTC, GaHee99 requested changes
count 업데이트..기디리겠습니다

2023-01-06 05:24 UTC, GaHee99 commented on .prettierrc.json
> +    "printWidth": 100,
ㅋㅋㅋㅋㅋㅋ꼼꼼해~~

2023-01-06 05:24 UTC, GaHee99 commented on src/constants/responseMessage.ts
> +    PICTURE_NOT_EXIST: "사진이 없습니다.",
개수 초과 ㅇㅈㅇㅈ 
트랜잭션 기대하겠습니다~

2023-01-06 05:24 UTC, GaHee99 commented on src/controller/stickerController.ts
> +        return res.status(sc.BAD_REQUEST).send(fail(sc.BAD_REQUEST, rm.STICKER_COUNT_EXCEED));
스티커 0개 넘어와도 처리하는 거 있으면 좋을 것 같아요~

2023-01-06 05:24 UTC, GaHee99 commented on src/router/stickerRouter.ts
> +    [body("emoji").notEmpty(), body("pictureId").notEmpty(), body("location").notEmpty()],
좋아요

2023-01-06 05:24 UTC, GaHee99 commented on src/service/stickerService.ts
> +const updateSticker = async (
Picture count +1 해주세용~

2023-01-06 05:24 UTC, GaHee99 commented on src/service/stickerService.ts
> +const updateSticker = async (
Vote count +1 해주세요~

2023-01-06 05:24 UTC, GaHee99 commented on src/service/stickerService.ts
> +const updateSticker = async (
트랜잭션 알려주세요~

2023-01-06 06:16 UTC, wlwpfh approved these changes

2023-01-07 05:39 UTC, merged